export const PLAY_ICON = '<icon:play.png>'
export const PLAY_ICON_GRAY = '<icon:play-gray.png>'
export const PAUSE_ICON_GREEN = '<icon:pause-green.png>'
export const STOP_ICON_GREEN = '<icon:stop-green.png>'
export const LOOP_ICON = '<icon:loop.png>'
export const LOOP_ICON_GRAY = '<icon:loop-gray.png>'
export const LOOP_ICON_GREEN = '<icon:loop-green.png>'

export const PROGRESS_0 = '<icon:progress/0.png>'
export const PROGRESS_1 = '<icon:progress/1.png>'
export const PROGRESS_2 = '<icon:progress/2.png>'
export const PROGRESS_3 = '<icon:progress/3.png>'
export const PROGRESS_4 = '<icon:progress/4.png>'
export const PROGRESS_5 = '<icon:progress/5.png>'
export const PROGRESS_6 = '<icon:progress/6.png>'
export const PROGRESS_7 = '<icon:progress/7.png>'
export const PROGRESS_8 = '<icon:progress/8.png>'
