import type { CompanionVariableDefinitions } from '@companion-module/base'
import { SECTION_PRESET_COUNT, SONG_PRESET_COUNT } from './constants.js'
import { makeRange } from './utils/range.js'

export const variables: CompanionVariableDefinitions = {
	totalHosts: { name: 'Total Hosts' },
	connectedHosts: { name: 'Connected Hosts' },

	beatsPosition: { name: 'Playhead Position in Beats' },
	finePosition: { name: 'Fine Playhead Position in Beats, Needs "Fine Updates" Option to be Enabled' },
	humanPosition: { name: 'Playhead Position in Bars.Beats' },
	humanPositionBeats: { name: 'Beats Part of the Playhead Position' },
	currentMeasure: { name: 'Current Measure in Bars.Beats, taken from a measure track if available' },
	currentMeasureBeats: { name: 'Beats Part of the Current Measure' },
	currentMeasureTotalBeats: { name: 'Number of Beats in the Current Measure' },
	currentMeasureOrPosition: {
		name: 'Current Measure if a Measure Track Exists, Otherwise Human Position',
	},
	currentMeasureOrPositionBeats: {
		name: 'Beats of Current Measure if a Measure Track Exists, Otherwise Beats of Human Position',
	},
	tempo: { name: 'Current Tempo' },
	isPlaying: { name: 'Is Playing' },
	isRecording: { name: 'Is Recording' },
	timeSignature: { name: 'Time Signature' },
	timeSignatureNumerator: { name: 'Time Signature Numerator' },
	timeSignatureDenominator: { name: 'Time Signature Denominator' },

	setlistName: { name: 'Setlist Name' },
	activeSongName: { name: 'Active Song Name' },
	activeSongIndex: { name: 'Active Song Index' },
	activeSongStart: { name: 'Active Song Start' },
	activeSongEnd: { name: 'Active Song End' },
	queuedSongName: { name: 'Queued Song Name' },
	queuedSongIndex: { name: 'Queued Song Index' },

	activeSectionName: { name: 'Active Section Name' },
	activeSectionIndex: { name: 'Active Section Index' },
	activeSectionStart: { name: 'Active Section Start' },
	activeSectionEnd: { name: 'Active Section End' },
	queuedSectionName: { name: 'Queued Section Name' },
	queuedSectionIndex: { name: 'Queued Section Index' },

	...Object.fromEntries(makeRange(SONG_PRESET_COUNT).map((i) => [`song${i + 1}Name`, { name: `Song ${i + 1} Name` }])),
	...Object.fromEntries(
		makeRange(SECTION_PRESET_COUNT).map((i) => [`section${i + 1}Name`, { name: `Section ${i + 1} Name` }]),
	),

	nextSongName: { name: 'Next Song Name' },
	nextSongName2: { name: '2nd Next Song Name' },
	nextSongName3: { name: '3rd Next Song Name' },
	nextSongName4: { name: '4th Next Song Name' },
	nextSongName5: { name: '5th Next Song Name' },
	nextSongName6: { name: '6th Next Song Name' },
	nextSongName7: { name: '7th Next Song Name' },
	nextSongName8: { name: '8th Next Song Name' },
	previousSongName: { name: 'Previous Song Name' },
	previousSongName2: { name: '2nd Previous Song Name' },
	previousSongName3: { name: '3rd Previous Song Name' },
	previousSongName4: { name: '4th Previous Song Name' },
	previousSongName5: { name: '5th Previous Song Name' },
	previousSongName6: { name: '6th Previous Song Name' },
	previousSongName7: { name: '7th Previous Song Name' },
	previousSongName8: { name: '8th Previous Song Name' },

	nextSectionName: { name: 'Next Section Name' },
	nextSectionName2: { name: '2nd Next Section Name' },
	nextSectionName3: { name: '3rd Next Section Name' },
	nextSectionName4: { name: '4th Next Section Name' },
	nextSectionName5: { name: '5th Next Section Name' },
	nextSectionName6: { name: '6th Next Section Name' },
	nextSectionName7: { name: '7th Next Section Name' },
	nextSectionName8: { name: '8th Next Section Name' },
	previousSectionName: { name: 'Previous Section Name' },
	previousSectionName2: { name: '2nd Previous Section Name' },
	previousSectionName3: { name: '3rd Previous Section Name' },
	previousSectionName4: { name: '4th Previous Section Name' },
	previousSectionName5: { name: '5th Previous Section Name' },
	previousSectionName6: { name: '6th Previous Section Name' },
	previousSectionName7: { name: '7th Previous Section Name' },
	previousSectionName8: { name: '8th Previous Section Name' },

	loopEnabled: { name: 'Loop Enabled' },
	loopStart: { name: 'Loop Start' },
	loopEnd: { name: 'Loop End' },
	isCountingIn: { name: 'Is Counting In' },

	audioInterfaceConnected: { name: 'Audio Interface Connected' },
	audioInterfaceScene: { name: 'Audio Interface Scene' },

	playAudio12Connected: { name: 'PlayAUDIO12 Connected (deprecated)' },
	playAudio12Scene: { name: 'PlayAUDIO12 Scene (deprecated)' },

	isSyncingPlayback: { name: 'Is Syncing Playback to Other Computer' },

	timecode: { name: 'Timecode' },
	timecodeHours: { name: 'Timecode Hours' },
	timecodeMinutes: { name: 'Timecode Minutes' },
	timecodeSeconds: { name: 'Timecode Seconds' },
	timecodeFrames: { name: 'Timecode Frames' },
	timecodeFps: { name: 'Timecode FPS' },
	timecodeStale: { name: 'Timecode Stale' },

	remainingTimeInSong: { name: 'Remaining Time in Song' },
	remainingTimeInSet: { name: 'Remaining Time in Set' },

	ableNet: { name: 'AbleNet Enabled' },
	ableNetDriftCorrection: { name: 'AbleNet Drift Correction' },
	autoplay: { name: 'Autoplay' },
	safeMode: { name: 'Safe Mode' },
	alwaysStopOnSongEnd: { name: 'Always Stop on Song End' },
	autoJumpToNextSong: { name: 'Autojump to the Next Song' },
	countIn: { name: 'Count-In' },
	countInSoloClick: { name: 'Solo Click During Count-In' },
	countInDuration: { name: 'Count-In Duration' },
	jumpMode: { name: 'Jump Mode' },
	removePlayedSongs: { name: 'Remove Played Songs Automatically' },
	autoReEnableAutomationOnSongJump: { name: 'Re-Enable Automation on Song Jump' },
	autoBackToArrangementOnSongJump: { name: 'Reset Tracks Back to Arrangement on Song Jump' },
	showStopButton: { name: 'Stop by Default Instead of Pausing' },
}
